######################################################################
# Automatically generated by qmake (3.0) ?? ???. 7 09:49:23 2018
######################################################################

TEMPLATE = app
TARGET = MyClient
INCLUDEPATH += .

# Input
HEADERS += myclient.h
SOURCES += main.cpp myclient.cpp \
    AuthorizationWindow.cpp
QT += widgets\
      core\
      network
CONFIG +=c++11
CONFIG += console
CONFIG -= app_bundle




